-- Schema initialization

create table if not exists events (
    id bigint generated by default as identity primary key,
    title varchar(150) not null,
    description text,
    start_date date not null,
    end_date date not null,
    hall varchar(100),
    ticket_price numeric(10,2),
    tickets_total int,
    tickets_sold int,
    image_url varchar(255)
);

create table if not exists exhibitions (
    id bigint generated by default as identity primary key,
    title varchar(150) not null,
    description text,
    hall varchar(100),
    status varchar(20) not null,
    image_url varchar(255),
    constraint chk_exhibition_status check (status in ('PERMANENT','TEMPORARY'))
);

create table if not exists tickets (
    id bigint generated by default as identity primary key,
    event_id bigint not null references events(id) on delete cascade,
    buyer_name varchar(100) not null,
    buyer_email varchar(100),
    status varchar(10) not null default 'SOLD',
    purchase_date timestamptz,
    constraint chk_ticket_status check (status in ('FREE','SOLD'))
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password_hash varchar(255) not null,
    role varchar(20) not null,
    email varchar(100) unique,
    constraint chk_user_role check (role in ('ADMIN','MANAGER','VISITOR'))
);

create table if not exists faq (
    id bigint generated by default as identity primary key,
    question varchar(255) not null,
    answer text,
    category varchar(100)
);

